const ISSUES = [
  {
    number: 81,
    title: "Tunel je hotový, cesta nie. Ružomberok znovu vidí, ako sa finále diaľnice mení na ďalšiu sezónu čakania.",
    date: "2026-04-19",
    dateLabel: "Nedeľa, 19. apríla",
    preview: "Tunel Čebrať je dokončený, no zosuv pri Likavke stále drží obchvat Ružomberka za plotom. Slovensko prevzalo poslednú F-16, dostalo prvú batériu Barak MX, samosprávy tlačia na zmenu dlhovej brzdy a Bratislavský kraj odmietol spaľovňu Slovnaftu.",
  },
  {
    number: 80,
    title: "Voľné miesta nestačia, keď fabrika odíde. Figaro ukazuje, ako sa výroba stráca po kusoch.",
    date: "2026-04-18",
    dateLabel: "Sobota, 18. apríla",
    preview: "Figaro presúva výrobu z Trnavy do Rohatca, februárové dáta stále ukazujú slabší priemysel a zamestnanosť klesá aj tam, kde mzdy rastú. Slovensko prevzalo poslednú F-16, dostalo prvý Barak MX a hotely mali rekordný február.",
  },
  {
    number: 79,
    title: "Nafta už nejde po 400 eur, no núdza zostáva. Štát ruší brzdu, necháva výnimku.",
    date: "2026-04-17",
    dateLabel: "Piatok, 17. apríla",
    preview: "Vláda ruší limit na tankovanie, ale necháva dvojité ceny. Eurofondy sú cez dve miliardy, podnikatelia naháňajú bezhotovostné platby a v Galante miznú ďalšie pracovné miesta.",
  },
  {
    number: 78,
    title: "Lacnejší odber už nebude na čestné slovo. Štát chce zvýhodnené energie len pre tých, čo ich naozaj míňajú doma.",
    date: "2026-04-16",
    dateLabel: "Štvrtok, 16. apríla",
    preview: "Vláda sprísňuje pravidlá pre domáce tarify na elektrinu a plyn, priznáva hlboký personálny problém v zdravotníctve a Agel ďalej rastie v Bratislave.",
  },
  {
    number: 77,
    title: "Družba sa má vrátiť do konca apríla. Slovensko však zisťuje, že stará trasa už nie je starý plán.",
    date: "2026-04-15",
    dateLabel: "Streda, 15. apríla",
    preview: "Zelenskyj sľubuje obnovenie Družby do konca apríla, no EÚ už kreslí cestu mimo nej. Slovenská pošta chystá záchranný plán, opozícia protestuje proti zmene voľby zo zahraničia a Bratislava rieši bezpečnosť mäkkých cieľov systematicky.",
  },
  {
    number: 76,
    title: "Orbán prehral za jednu noc to, čo držal šestnásť rokov. Pre Slovensko sa mení sused aj regionálna rovnica.",
    date: "2026-04-14",
    dateLabel: "Utorok, 14. apríla",
    preview: "Maďarská Tisza získala 138 zo 199 kresiel a ústavnú väčšinu, Fico aj Blanár už hovoria o spolupráci s novou vládou a budapeštianske trhy otvorili rekordným rastom. Slovensko vo Vietname ponúka jadro aj zbrojárstvo, v Pezinku sa začal proces po útoku na škole a Eximbanka vlani podporila export takmer za dve miliardy eur.",
  },
  {
    number: 75,
    title: "Bez školy nebudú dávky. Štát skúša pritvrdiť tam, kde dlhodobo zlyháva dochádzka.",
    date: "2026-04-13",
    dateLabel: "Pondelok, 13. apríla",
    preview: "Rezort práce chce po troch mesiacoch záškoláctva presmerovať prídavok na dieťa a po ďalších troch ho odňať. Fico začal návštevu Vietnamu, obranná debata sa posúva od ústavy k zákonom a spor o voľbu zo zahraničia sa vracia do parlamentu.",
  },
  {
    number: 74,
    title: "Nemocnice sa nestavajú na jedno volebné obdobie. Pellegrini skúša vynútiť dohodu tam, kde Slovensko už raz nechalo skelet.",
    date: "2026-04-12",
    dateLabel: "Nedeľa, 12. apríla",
    preview: "Prezident chce podpis koalície aj opozície pod dostavbu strategických nemocníc aj po voľbách v roku 2027. V Prešove vypli kľúčové semafory, Schengen prešiel na digitálny vstupný systém a maďarské voľby prichádzajú s najtesnejším napätím za roky.",
  },
  {
    number: 73,
    title: "Priemysel znovu spomalil. Slovensko vidí, aké drahé je stáť na jednom motore.",
    date: "2026-04-11",
    dateLabel: "Sobota, 11. apríla",
    preview: "Priemyselná produkcia vo februári klesla o 2,9 percenta a auto sektor znovu ukázal, aké drahé je stáť na jednom motore. Bratislavské letisko má rekordné leto, vláda chystá reakciu na drahšie palivá a veterinári zhadzujú takmer 400-tisíc návnad proti besnote.",
  },
  {
    number: 72,
    title: "Nemocnice dlhujú za pomôcky vyše sto miliónov. Audit len ukázal, čo sa roky odkladalo.",
    date: "2026-04-10",
    dateLabel: "Piatok, 10. apríla",
    preview: "Štátne nemocnice dlhujú za zdravotnícke pomôcky 109 miliónov eur a audit piatich zariadení dopadol zle. Gastrolístky už na obed väčšinou nestačia, vláda stiahla lacnejšie vlaky, ropná núdza stále trvá a na Málinci sa chystá ďalší veľký spor.",
  },
  {
    number: 71,
    title: "Do školy po schodoch. Pre desaťtisíce detí je bežná trieda stále za bariérou.",
    date: "2026-04-09",
    dateLabel: "Štvrtok, 9. apríla",
    preview: "Na bežné školy chodí 61 500 detí so zdravotným znevýhodnením, no na takmer 90 percentách budov sú stále len schody. Autobusy na Schwechat zlacneli, Huliak chce siahnuť na odpočty DPH, domácnosti riešia vyššie zálohy za teplo a štátne dlhopisy si tento rok kúpilo 22 100 ľudí.",
  },
  {
    number: 70,
    title: "Ukrajinci na Slovensku už nie sú len náklad. Štátu prinášajú viac, než stála pomoc.",
    date: "2026-04-08",
    dateLabel: "Streda, 8. apríla",
    preview: "Pracujúci Ukrajinci odvedú tento rok na daniach a odvodoch viac, než štát minul na pomoc utečencom od začiatku invázie. Banky ustupujú od klasických platobných kariet, firma Proxenta nevypláca dlhopisy a košické letisko už ponúka dvanásť pravidelných destinácií.",
  },
  {
    number: 69,
    title: "Veľké firmy na Slovensku platia v regióne najviac. A tým sa problém len začína.",
    date: "2026-04-07",
    dateLabel: "Utorok, 7. apríla",
    preview: "Veľké firmy na Slovensku čelia najvyššej dani z príjmu v postkomunistickom regióne a po započítaní transakčnej dane sa zaťaženie približuje k 26 percentám. Martinská Neografia opäť prepúšťa, Bratislava zjemňuje prvé pokuty v PAAS a kultúrny protest v hlavnom meste prilákal podľa odhadov 14-tisíc ľudí.",
  },
  {
    number: 68,
    title: "Vo vlastnom, no stiesnene. Slovenské bývanie zdraželo a ponuka nestíha.",
    date: "2026-04-06",
    dateLabel: "Pondelok, 6. apríla",
    preview: "Na Slovensku býva vo vlastnom až 93 percent ľudí, no 30 percent obyvateľov žije v preplnených domácnostiach a dopyt po bytoch stále prevyšuje ponuku. Pellegrini zvoláva okrúhly stôl k stavu ohrozenia, trh s jazdenými autami sa prepadol o 15 percent a jedenásť vedcov zo STU je v stanfordskom rebríčku najvplyvnejších.",
  },
  {
    number: 67,
    title: "Veľkonočný stôl je čoraz viac z dovozu. Slovensko si vyrába menej jedla, než potrebuje.",
    date: "2026-04-05",
    dateLabel: "Nedeľa, 5. apríla",
    preview: "Potravinári varujú, že Slovensko je čoraz závislejšie od dovozu potravín a rekordne sa mu prehlbuje agropotravinársky deficit. Pellegrini zvoláva okrúhly stôl k stavu ohrozenia, trh s jazdenými autami sa prepadol o 15 percent a STU má jedenásť vedcov v stanfordskom rebríčku najvplyvnejších.",
  },
  {
    number: 66,
    title: "Rast len na percento. Slovensko sa tento rok opiera o plán obnovy a Volvo.",
    date: "2026-04-04",
    dateLabel: "Sobota, 4. apríla",
    preview: "Ministerstvo financií čaká tento rok rast ekonomiky len o 1 percento HDP, pričom hlavnú oporu vidí v pláne obnovy a budúcich exportoch z Volva. Trh s jazdenými autami sa v marci prepadol o 15 percent, Pellegrini zvoláva okrúhly stôl k stavu ohrozenia a jedenásť vedcov zo STU sa dostalo do stanfordského rebríčka najvplyvnejších.",
  },
  {
    number: 65,
    title: "Štát si už požičal 4,4 miliardy. A to je len prvý štvrťrok.",
    date: "2026-04-03",
    dateLabel: "Piatok, 3. apríla",
    preview: "Slovensko má za prvé tri mesiace predaných štátnych dlhopisov už za 4,441 miliardy eur, teda takmer polovicu ročného plánu. Nafta pre zahraničné autá od polnoci opäť zdražela, Artemis II už mieri k Mesiacu a Péter Magyar mení maďarské voľby na spor o smer celej krajiny.",
  },
  {
    number: 64,
    title: "Atóm späť do štátu. Bohunice sa chystajú bez ČEZ-u.",
    date: "2026-04-02",
    dateLabel: "Štvrtok, 2. apríla",
    preview: "JESS sa má ešte tento polrok dostať plne do rúk štátu, keďže sa pripravuje odkúpenie 49-percentného podielu ČEZ-u. Od apríla sa rozširuje ošetrovné, pri slovenskej hranici spadol dron a Artemis II v noci odštartovala s ľudskou posádkou k Mesiacu.",
  },
  {
    number: 63,
    title: "Plastová karta už nemusí byť samozrejmosťou. Banky ju menia na príplatok.",
    date: "2026-04-01",
    dateLabel: "Streda, 1. apríla",
    preview: "Banky postupne znižujú počet fyzických debetných kariet a niektoré ich začínajú spoplatňovať. Vyššie zdravotné odvody ukrojili z čistých miezd, domácnostiam vyskočili zálohy za teplo a Brusel tlačí na Slovensko, aby zrušilo dvojaké ceny nafty.",
  },
  {
    number: 62,
    title: "Slovensku chýbajú sestry. Ukrajinky brzdí byrokracia.",
    date: "2026-03-31",
    dateLabel: "Utorok, 31. marca",
    preview: "Slovensku dnes chýba približne 2 800 zdravotných sestier a deficit môže do roku 2040 narásť až na 20-tisíc. Demokrati odovzdali prezidentovi 384 314 podpisov za referendum, marcový model znovu ukazuje tesný súboj PS a Smeru a firmy chcú od vlády manuál k sviatkom bez voľna, ale s príplatkami.",
  },
  {
    number: 61,
    title: "Aprílové dôchodky rozhádže Veľká noc. Tisíce seniorov si aj prilepšia.",
    date: "2026-03-30",
    dateLabel: "Pondelok, 30. marca",
    preview: "Časť aprílových dôchodkov sa pre Veľkú noc posunie a približne 155- až 156-tisíc pracujúcich dôchodcov dostane zvýšenie penzie aj s doplatkom od januára. Vláda sa stále nechystá požiadať parlament o dôveru, firma v Dubnici dlhuje mzdy od októbra a Srbsko znervóznilo región čínskymi raketami.",
  },
  {
    number: 60,
    title: "Štát si posvieti na invalidné dôchodky. Tvrdí, že šetrí, ľudia počujú šikanu.",
    date: "2026-03-29",
    dateLabel: "Nedeľa, 29. marca",
    preview: "Ministerstvo práce chce po kontrolách PN dôslednejšie preverovať aj invalidné dôchodky a argumentuje úsporami v desiatkach miliónov eur. Otvorenie diaľnice pri Ružomberku sa opäť odkladá, Republika rastie zo sklamaných voličov koalície a G7 vo Francúzsku rieši Irán aj Ukrajinu.",
  },
  {
    number: 59,
    title: "Slovenská ekonomika vlani skoro stála. Rast spadol na 0,8 percenta.",
    date: "2026-03-28",
    dateLabel: "Sobota, 28. marca",
    preview: "Slovenský HDP vlani vzrástol len o 0,8 % a domácnosti podľa Štatistického úradu citeľne ubrali zo spotreby. Slovensko berie zo zimnej paralympiády tri bronzy, všetky získala Alexandra Rexová. G7 vo Francúzsku rieši Irán aj Ukrajinu a EÚ od 1. mája spúšťa dohodu s Mercosurom.",
  },
  {
    number: 58,
    title: "Slovensko viedlo dvakrát. Na MS aj tak nepôjde.",
    date: "2026-03-27",
    dateLabel: "Piatok, 27. marca",
    preview: "Slovensko prehralo doma s Kosovom 3:4 a končí v baráži o MS 2026. Slovenská ekonomika vlani rástla len o 0,8 %. Europarlament odobril dohodu EÚ-USA a G7 vo Francúzsku rieši Irán aj Ukrajinu.",
  },
  {
    number: 57,
    title: "Poslanec s 45-tisíc eurami v garáži. Ferenčák tvrdí, že šlo o pôžičku.",
    date: "2026-03-26",
    dateLabel: "Štvrtok, 26. marca",
    preview: "Na sociálnych sieťach koluje video, kde poslanec Ferenčák odovzdáva 45 000 eur v hotovosti. Slovensko zdvojnásobilo cenu nafty pre cudzincov — Brusel pohrozil konaním. EP schválil dohodu Turnberry s USA. Dnes večer Slovensko hrá o MS 2026 s Kosovom.",
  },
  {
    number: 56,
    title: "Slovensko žaluje Úniu. Fico napadol zákaz ruského plynu na Súdnom dvore EÚ.",
    date: "2026-03-25",
    dateLabel: "Streda, 25. marca",
    preview: "Fico podal žalobu na EÚ Court pre zákaz ruského plynu — tvrdí, že Brusel obišiel jednomyseľnosť. Slovenská inflácia mierne klesla na 3,7 %. EP hlasuje o obchodnej dohode s USA.",
  },
  {
    number: 55,
    title: "SaS podala trestné oznámenie na Fica pre vlastizradu. A Pellegrini sám žiadal Kremlin o pomoc pred voľbami.",
    date: "2026-03-24",
    dateLabel: "Utorok, 24. marca",
    preview: "Bratislavská prokuratúra preberá prípad velezrady premiéra Fica. Pellegrini sám žiadal Orbána o pomoc od Kremľa — je dnes prezidentom. Slovensko žiada inšpekciu ropovodu Džba.",
  },
  {
    number: 54,
    title: "Jansša nedokázal vyhrať. Golob nedokázal presvedčiť. Slovinsko sa prebudilo do nerozhodna.",
    date: "2026-03-23",
    dateLabel: "Pondelok, 23. marca",
    preview: "Slovinské voľby skončili najtesnejším výsledkom za desaťročia — Golob a Jansša sú od seba vzdialení menej ako tri percentá. Ak Jansša zostaví vládu, Orbán má nového spojenca. Fico medzitým pohrozil vetom 90 miliárd pre Ukrajinu. Česko ponúka Slovensku nový ropovod. A Kuba ostala bez svetla — po tretíkrát tento mesiac.",
  },
  {
    number: 53,
    title: "Hormuz musí byť otvorený do 48 hodín. Inak Trump zasiahne elektrárne.",
    date: "2026-03-22",
    dateLabel: "Nedeľa, 22. marca",
    preview: "Dvadsaťtretí deň vojny USA a Izraela s Iránom. Trump dal Teheránu 48 hodín na otvorenie Hormuzského prielivu — inak zasiahne iránske elektrárne. Brent na 112 dolároch. V Prahe 250 000 demonštrantov hovorí: nechceme sa stať Slovenskom.",
  },
  {
    number: 52,
    title: "Orbán vyhral summit. Únia odišla domov s prázdnymi rukami.",
    date: "2026-03-21",
    dateLabel: "Sobota, 21. marca",
    preview: "Dvojdňový summit EÚ skončil bez dohody o úvere 90 miliárd eur pre Ukrajinu. Záverečné závery podpísalo 25 z 27 štátov — Maďarsko a Slovensko nie. Orbán odchádzal v dobrej nálade.",
  },
  {
    number: 51,
    title: "Prídely nafty od dnes. Slovensko zaviedlo núdzový režim na čerpačkách.",
    date: "2026-03-20",
    dateLabel: "Piatok, 20. marca",
preview: "Od dnešného rána platia na slovenských čerpacích staniciach opatrenia, aké sme tu ešte nemali — prídely nafty, zákaz exportu a vyššie ceny pre cudzincov. Ropovod Družba zostáva prázdny. Je prvý deň jari.",
  },
    {
    number: 50,
    title: "Orbán prišiel do Bruselu. A priniesol si „nie\".",
    date: "2026-03-17",
    dateLabel: "Streda, 18. marca",
    preview: "Dnes v Bruseli zasadá summit lídrov EÚ — a ešte pred prvým kávou je jasné, že to nebude nudné. Maďarský premiér Viktor Orbán prišiel s jasnou správou: kým Kyjev neobnoví toky ruskej ropy cez ropovod Družba, Maďarsko nezruší veto na pôžičku 90 miliárd eur pre Ukrajinu.",
  },
  {
    number: 492,
    title: "Praha ide na miesto činu. Bratislava čaká, čo nájdu.",
    date: "2026-03-17",
    dateLabel: "Utorok, 17. marca",
    preview: "Česko ponúklo viesť európsku inšpekčnú misiu priamo na poškodený ropovod Družba na Ukrajine — Slovensko bez ruskej ropy už takmer 50 dní. Doma Danko po sneme znovu kritizuje Fica, ale vládu nepovalí. A ropa Brent prekonala 100 dolárov.",
  },
  {
    number: 49,
    title: "Spojenci povedali nie. A Trump im pohrozil zlou budúcnosťou.",
    date: "2026-03-17",
    dateLabel: "Utorok, 17. marca",
    preview: "Európa povedala Trumpovi nie — spojenci odmietli vyslať vojnové lode do Hormuzského prielivu a ceny ropy prekonali 100 dolárov. Doma Fico mení 20-ročný postoj a chce zo štátnych nemocníc akciové spoločnosti, lebo ich dlhy presiahli miliardu eur.",
  },
  {
    number: 48,
    title: "Slovensko ustúpilo. Alebo teda — skoro.",
    date: "2026-03-16",
    dateLabel: "Pondelok, 16. marca",
    preview: "Bratislava cez víkend pustila brzdu na sankciách EÚ, hoci chcela vyradiť Fridmana a Usmanova. Spor o ropovod Družba medzitým mení diplomaciu na servis potrubia. A Wizz Air dnes otvára nové linky z Bratislavy.",
  },
  {
    number: 3,
    title: "Nový zákon o daniach, Tesla lacnie, Slovan v osemfinále",
    date: "2025-03-05",
    dateLabel: "Streda, 5. marca",
    preview: "Zmeny daní sa dotknú 85 000 živnostníkov. Tesla znížila ceny v EÚ o 8%. Slovan postúpil do osemfinále Európskej ligy.",
  },
  {
    number: 2,
    title: "Voľby sa blížia, AI Act finalizovaný, Tesla lacnie",
    date: "2025-03-04",
    dateLabel: "Utorok, 4. marca",
    preview: "Predvolebná kampaň naberá tempo. EÚ dokončila AI Act. Tesla znížila ceny v Európe.",
  },
  {
    number: 1,
    title: "Digitálna identita, inflácia padá, Resco získal 8M€",
    date: "2025-03-03",
    dateLabel: "Pondelok, 3. marca",
    preview: "Parlament schválil zákon o eID. Inflácia na najnižšej hodnote od 2021. Bratislavský startup Resco pokračuje v expanzii.",
  }
];

function getIssueArchivePath(issue) {
  if (!issue || !issue.date) return null;
  const parts = issue.date.split('-');
  if (parts.length !== 3) return null;
  return `/archiv/${parts[2]}/${parts[1]}/${parts[0]}/#issue-${issue.number}`;
}

function getIssueByNumber(number) {
  return ISSUES.find(issue => issue.number === Number(number)) || null;
}
